### PR TITLE
Update lda.c

### PR DESCRIPTION
**Pull request by MPurcell-EDR**

### CODE REVIEW

**Comment by kshirley** [comment]
Hi,

Thanks for the suggestion. Looks like using rand() will be more portable than using drand48() -- was that the idea? I just looked at a SO post here, though, and I think we want to replace RAND_MAX + 1.0 with just RAND_MAX:

http://stackoverflow.com/questions/9878965/c-rand-between-0-and-1

If you agree and change it, I'll merge.

PS. Just a heads-up, though: I'm not really developing this package anymore -- it was more just for practice in learning how to write an R package. There are a couple better R packages for fitting LDA, like `lda` and `topicmodels` that I'd suggest you use if you're interested in doing some topic modeling in R. If you want to visualize the results of an LDA model, by chance, then check out cpsievert/LDAvis, which is still being supported and developed.

cheers,
kenny

**Comment by mpurcell92** [comment]
Yes exactly the idea, and yes I’ve been using those tools also. The reason I was interested in this version, like many others, is for the clustering ability (regardless of the flaws that may be presented switching from 3d to 2d).  I really have enjoyed using these packages, and thank you for your time in developing and maintaining them. I know I speak for a great number of people when I say this! Let me know when you decide to merge it, and yes RAND_MAX seems the best option. Thanks for your response!
-Matt

**Comment by kshirley** [comment]
Cool, thanks, Matt. I appreciate the kind words -- glad you're enjoying the tools.

Will merge and then will edit to RAND_MAX instead of (RAND_MAX + 1.0).

k

**Comment by mpurcell92** [comment]
Still having trouble running it on windows. I know you’re not trying to put more time into this version so I completely understand if you don’t want to change the code. I’m guessing its working fine on your computer, my error was as follows:
lda.c: In function 'sample':
lda.c:247:17: error: expected ')' before 'rand'
lda.c:247:37: error: expected expression before ';' token
make: *** [lda.o] Error 1

Thanks again for your time, it’s definitely one step further to running well on windows.
-Matt

**Comment by kshirley** [comment]
Ack, thanks. It was a typo. Fixed now and it installs on my machine. Does it work for you?

**Comment by MPurcell-EDR** [comment]
Yes works Great! Thank you so much, can’t wait to get started.
-Matt

**Pull request merged**
